# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7,3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-annotations pytest black
        pip install .[test]
    - name: Lint with flake8
      run: |
        python -m flake8 . --count --max-line-length=88 --ignore=E203,E501,ANN101,ANN102,ANN002,ANN003 --show-source --statistics
    - name: Black check
      run: |
        python -m black --check .
    - name: Test with pytest
      run: |
        pytest
    - name: Test coverage
      run: |
        python3 -m pytest --cov=. --cov-fail-under=85 -m 'not integration'
